 @startuml
'https://plantuml.com/class-diagram

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x

hide methods

entity DimDate {
    primary_key(date_key)
    full_date
    year
    semester
    quarter
    month
    month_name
    week
    week_name
    day_number_of_year
    day_number_of_month
    day_number_of_week
    day_of_week
    weekend
}

entity DimCustomer {
    primary_key(customer_key)
    customer_code
    customer_type
    name
    number
    email
    address
    city
    location
    zip_code
    tax_payer_number
    phone
    contact
    fax
    email
    effective_date
    expired_date
    is_current
}

entity DimProduct {
    primary_key(product_key)
    product_code
    unit_price
    start_selling_date
    stock
    family_code
    family_name
    description
    order_point
    minimum_stock
    category
    effective_date
    expired_date
    is_current
}

entity DimEmployee {
    primary_key(employee_key)
    number
    initials
    employee_code
    forename
    surname
    group
    email
    department
    department_code
    effective_date
    expired_date
    is_current
}

entity FactSales {
    primary_key(foreign_key(date_key))
    primary_key(foreign_key(customer_key))
    primary_key(foreign_key(product_key))
    primary_key(foreign_key(employee_key))
    foreign_key(customer_number)
    foreign_key(employee_number)
    foreign_key(product_code)
    sale_id
    sale_line_id
    sale_date
    quantity
    unit_price
    line_value
    payment_date
    products_total_value
    vat
    vat_rate
    final_value
    total_amount
}

FactSales "*" -left- "1" DimCustomer
FactSales "*" -up- "1" DimDate
FactSales "*" -right- "1" DimProduct
FactSales "*" -down- "1" DimEmployee

@enduml